MYSQL_HOST = 'localhost'
MYSQL_USER = 'root'
MYSQL_PASSWORD = '@Aniket2201'
MYSQL_DB = 'ved'
SECRET_KEY = '1234'


admin = 'admin.html'
attendance = 'attendance.html'
change_pwd = 'change_pwd.html'
error = 'error.html'
home = 'home.html'
ocr = 'ocr.html'
student = 'student.html'
teacher_dashboard = 'teacher_dashboard.html'
teacher_login = 'teacher_login.html'
teacher_register = 'teacher_register.html'
update_profile = 'update_profile.html'
upload_sheet = 'upload_sheet.html'
user_details = 'user_details.html'
user_profile = 'user_profile.html'


admin_email = 'admin@gmail.com'
# msg

invalid_cred = 'Incorrect some E-mail/password!'
account = 'Account already exists!'
email = 'Invalid email address!'
username = 'Username must contain only characters and numbers!'
form = 'Please fill out the form!'
authenticate = 'Request for Authentication has been sent!'
update = 'Updated Successfully'
delete = 'Deleted Successfully'
add = 'Added Successfully'
error = 'Excel sheet not found'